name = "rizotto"
license = "MIT"
licenselink = "https://github.com/zfkdnop/rizotto/blob/master/LICENSE"
description = "A minimalist, responsive theme inspired by terminal ricing aesthetics and slightly modified for additional features."

homepage = "https://github.com/zfkdnop/rizotto"
demosite = "https://rizotto.joeroe.io"

tags = ["responsive", "minimal", "dark mode"]
features = []
min_version = "0.41.0"

[author]
  name = "zfk dnop"
  homepage = "https://lowkey.pub"

